### ISSUE TITLE
Bump version to 0.7.0 and upload to crates.io

### ISSUE THREAD

**Issue by bddap** [multiformats/rust-multibase#12]
The current version on crates.io is 0.6.0 and it lacks some of the improvements on the current master branch.

It would be nice to get new features like padded encodings on the crates.io.

**Comment by repi** [comment]
@dignifiedquire any update on this? would be great to have a new version published.

I'm sort of evaluating right now if we should use this crate or create our own small similar one that we maintain ourselves

**Comment by dignifiedquire** [comment]
sorry for the delay, just published 0.7.0

**Comment by repi** [comment]
Thanks!
