### ISSUE TITLE
Any plans to support no_std?

### ISSUE THREAD

**Issue by woss** [multiformats/rust-multibase#24]
i started using this lib together with rust-cid and rust-multihash on a [Substrate ](https://substrate.dev) project and i realised that you don't support `no_std` any plans to support that?

Thank you

**Comment by vmx** [comment]
There are no concrete plans, but PRs are certainly welcome.

**Comment by woss** [comment]
i'd love to contribute and improve my rust(y) skills but its quite hard to find a good tutorial on how to get started. if you have any resources please share. 
*NOTE* i managed to get it running on substrate based chain, but i would like to see it as a real `no_std`
