### ISSUE TITLE
Use macros, slim down fat

### ISSUE THREAD

**Issue by mriise** [multiformats/rust-multibase#26]
`impls.rs` could be cleaned up with macros, along with some other minor changes here and there around the repo.

It could also get the same treatment as https://github.com/multiformats/rust-multihash where each base code is a feature, which may be useful for those looking to use `no_std` to slim down crate size although that might be a bit overkill.

I'd be interested in making these changes but figured opening an issue first before making a large PR would be better than not, especially if people are interested in helping out.

**Comment by vmx** [comment]
I generally find less macros better (while in rust-multihash there's plenty of macros). Though in this case in Macros make sense as it is really repetitive. I think if the macros are kept simple, it could make things easier to read and maintain.

I'm not sure about each base code being its own feature. The reason for rust-multihash doing it this way is, that every hash algorithm draws in its own dependencies. Also you're encourage to specify your own code table, with only the hashers you want.

Here we have two dependencies for the hashing. So perhaps there could be two features, one for each encoding library. Though I'm not sure how useful in comparison to how confusing it will be.

So I suggest starting with a PR introducing macros and thinking about new feature flags later on.
