### ISSUE TITLE
Encoding ambiguity due to underlying design

### ISSUE THREAD

**Issue by eth-r** [multiformats/rust-multibase#5]
The truncation of leading zeros in the base-x package this library is built with creates an ambiguous encoding. This is especially noticeable in base-2 where the example test case `"yes mani !"` encodes to `"01111001011001010111001100100000011011010110000101101110011010010010000000100001"`, while a strict encoding would be `"001111001011001010111001100100000011011010110000101101110011010010010000000100001"`. This means that decoding `"\x00yes mani !"` results in `"yes mani !"`, an erroneous interpretation in many contexts.

More info: https://github.com/multiformats/multibase/issues/34

**Comment by wigy-opensource-developer** [comment]
The following test passes with multibase 0.6.0

```rust
#[test]
fn does_not_truncate_leading_zeroes() {
    let data = b"\x00yes mani !";
    let output = multibase::encode(multibase::Base2, data);
    let (base, decoded) = multibase::decode(output).unwrap();

    assert_eq!(base, multibase::Base2);
    assert_eq!(&decoded, data);
}
```

Does that mean that this issue is already fixed, @eth-r ?

**Comment by vmx** [comment]
This issue seems to be fixed, as there is a test for this case now. Hence I'm closing this issue, please re-open if I missed something.
