### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by dvc94ch** [multiformats/rust-multibase#9]
So I implemented the ipld multiblock vector and did some benchmarks. Here are the results from my dell xps where > means faster.

cbor > json
blake2s > sha2-256 > blake2b

Interestingly most of time is spent on base encoding (by a margin).

Here is what I flamegraphed for reference:
```rust
use criterion::black_box;
use ipld_vec::{mock::Store, Vector};
use libipld::{DefaultPrefix, Ipld};

type IpldVec = Vector<DefaultPrefix, Store>;

fn main() {
    // push: 1024xi128; n: 4; width: 256; size: 4096
    let mut vec = IpldVec::new(256).unwrap();
    for i in 0..1024 {
        vec.push(Ipld::Integer(i as i128)).unwrap();
    }
    black_box(vec);
}
```
![flamegraph](https://user-images.githubusercontent.com/741807/64294798-f7f72700-cf6f-11e9-9dbd-60410d3b8e5c.png)

It only uses a simple hashmap as block storage, it might not matter much once I implement a file system block storage.
NOTE: the bs58 crate is much slower.

**Comment by dvc94ch** [comment]
With the changes to multibase, switching to base64 and some improvements on the cbor codec the benchmark is 77% faster!
![flamegraph](https://user-images.githubusercontent.com/741807/64568720-bee9f880-d35b-11e9-80c7-8483bb61da9d.png)
The hash function is actually starting to make a difference, and blake2b is 3ms faster than sha2-256 (over the whole bench mark that is).

**Comment by dignifiedquire** [comment]
great, we should switch to the blake2_simd crates in multihashing, they are the fastest ones out there

**Comment by vmx** [comment]
I think this can be closed as https://github.com/multiformats/rust-multibase/pull/8 was merged.
